### ISSUE TITLE
alpine-node does not pin node and npm versions

### ISSUE THREAD

**Issue by lolmaus** [cirolosapio/devcontainers-features#59]
Thank you for the handy feature! 🙇 

It is possible to pin a specific version, but not for node and npm. It is a problem because different developers may receive different environments and see results inconsistent with each other.

Node and npm are installed via:

    apk --no-cache add nodejs npm

This command should be parameterized, so that a specific version of node and npm can be pinned in `devcontainer.json`.

🙏

**Comment by lolmaus** [comment]
https://github.com/cirolosapio/devcontainers-features/blob/d54c16c8ec234a62e2bda1b61e03a7d48fe64ee4/src/alpine-node/install.sh#L7

**Comment by cirolosapio** [comment]
I cannot find an official way to install a specific node/npm version
feel free to open PR 😄
