### ISSUE TITLE
Make devcontainer compatible with Wolfi base image

### ISSUE THREAD

**Issue by davzucky** [cirolosapio/devcontainers-features#69]
Thank you very much for making the dev container compatible with Alpine.

Wolfi is a base docker image that is based on glibc. It is used as well ```apk``` to install binary, which is similar to Alpine. However, some package names don't exist in the Wolfi registry. I would like to make them not mandatory or in the function of the distribution installing another binary,

What do you think about that? The first I found is ```docker-zsh-completion``` in the ```alpine-docker-outside-of-docker```.

**Comment by cirolosapio** [comment]
I will close this issue for now

feel free to reopen it again if it is not solved
